### ISSUE TITLE
Unsure of WordPress location

### ISSUE THREAD

**Issue by sixfootjames** [nditech/org.ndi.sms.telerivet#1]
Hi Michael,

You mentioned in the instructions to ask here if people are not sure of the Webhook URL. Would you mind pointing me in the right direction for WordPress please?

In your [Stack reply](https://civicrm.stackexchange.com/questions/24852/not-receiving-telerivet-sms-to-civicrm/24860#24860), you said it should be...

https://crm.helderberghospice.org.za/?page=CiviCRM&q=civicrm%2Fsms%2Fcallback&provider=org.ndi.sms.telerivet

But I have tried this option and not had much joy.

**EDIT:** When I do a test send of an sms, the preloader just sits and it does not submit form.

Many thanks

**Comment by michaelmcandrew** [comment]
Can you be more specific on what you mean by not had much joy?

**Comment by sixfootjames** [comment]
Added an EDIT above Michael, thank you

**Comment by michaelmcandrew** [comment]
the webhook looks right to me.

is this an incoming sms to civicrm? (the webhook is only used for incoming sms)

are you able to send sms from civicrm ok?

> the preloader just sits and it does not submit form.

sorry, not sure what this means - can you explain a bit more?

**Comment by sixfootjames** [comment]
Hi Michael, 

I did double check the web hook and it seems right now. When I hit the link directly I am not getting an error like before, so thanks for that.

I sent a link separately to you privately to show you what I mean by the preloader. This is when I am trying to send the SMS's

**Comment by michaelmcandrew** [comment]
Thanks for the gif.

So, a couple of things.

1. The webhook is only used for inbound SMS - not outbound SMS (which is what you showed me in the gif)
2. More than likely, the infinite preloader spinning logo thing is hiding a more useful error message.

You can see that error message if you do the following

Go to Actions Send SMS but right click and choose open link in new tab. It should open the same screen but in a form where you will get to see the error message. That should give you a clue as to what is happening. If you want to post back here any errors you see on that page, I can see if i can help further.
