### ISSUE TITLE
SMS Conversations is broken for PSCPD

### ISSUE THREAD

**Issue by turnerd** [nditech/org.ndi.sms.telerivet#3]
The site pscpd.demcloud.org has been a user of SMS Conversations but it is currently not working. They are able to send out an SMS, but when they reply they get no further messages.

**Comment by turnerd** [comment]
They received the following error notification from Telerivet:

> PSCPD Webhook Service was unable to automatically process an incoming SMS from +22509216780:
>
>HTTP 500 (https://pscpd.demcloud.org/civicrm/sms/callback?provider=org.ndi.sms.telerivet ): <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"> <head> <title></title> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <base href="https://pscpd.demcloud.org/sites/all/modules/contrib/civicrm/" /> <style type="text/css" media="screen"> @import url(https://pscpd.demcloud.org/sites/all/modules/contrib/civicrm/css/civicrm.css); @import url(https://pscpd.demcloud.org/sites/all/modules/contrib/civicrm/css/crm-i.css); @import url(https://pscpd.demcloud.org/sites/all/modules/contrib/civicrm/bower_components/font-awesome/css/font-awesome.min.css); </style> </head> <body> <div id="crm-container" class="crm-container" lang="fr" xml:lang="fr"> <div class="messages status no-popup"> <i class="crm-i fa-exclamation-triangle crm-i-red" aria-hidden="true"></i> <span class="status-fatal">Désolé, à cause d'une erreur, nous ne sommes pas en mesure, pour le moment, de satisfaire votre requête. Nous vous invitons à contacter votre administrateur système ou votre fournisseur de service en lui fournissant plus de détails sur l'action que vous étiez en train de réaliser quand cela est arrivé.</span> <div class="crm-section crm-error-message">Mandatory key(s) missing from params array: text</div> <p><a href="https://pscpd.demcloud.org/fr/" title="Menu principal">Retourner à la page d'accueil.</a></p> </div> </div> <script language="JavaScript"> function toggle( element ) { var parent = element.parentNode; var className = parent.className; if ( className == 'crm-accordion-wrapper collapsed crm-fatal-error-details-block') { parent.className = 'crm-accordion-wrapper crm-fatal-error-details-block'; } else { parent.className = 'crm-accordion-wrapper collapsed crm-fatal-error-details-block'; } } </script> </body> </html>

**Comment by turnerd** [comment]
screen capture in case the markdown altered the telerivet error message:
![image](https://user-images.githubusercontent.com/1743707/105732551-9174ff00-5efe-11eb-8bb9-0cf7ec95ba11.png)

**Comment by turnerd** [comment]
Because the civi webhook failed to respond it seems like the error is with Civi and not Telerivet. 
They attempted sending the SMS again but had the same problem, so it isn't a temporary outage.
So far I have tried 1) verifying the PSCPD site in Aegir and 2) confirming Civi's configuration of the Telerivet extension.

The conversation they are trying to use is this:
![image](https://user-images.githubusercontent.com/1743707/105733208-46a7b700-5eff-11eb-86b9-a002e64f519e.png)

**Comment by turnerd** [comment]
@mlutfy it appears I can't assign this issue to you because I am not a contributed to this repository

**Comment by mlutfy** [comment]
Here is what I see in the log file:

```
janv. 25 13:10:30  [error]
$Fatal Error Details = array(3) {
  ["message"]=>
  string(48) "Mandatory key(s) missing from params array: text"
  ["code"]=>NULL
  ["exception"]=>
  object(CiviCRM_API3_Exception)#967 (8) {
    ["extraParams":"CiviCRM_API3_Exception":private]=>
    array(6) {
      ["fields"]=> array(1) {
        [0]=>    string(4) "text"
      }
      ["error_code"]=>string(17) "mandatory_missing"
      ["entity"]=>  string(7) "Contact"
      ["action"]=>string(3) "sms"
      ["is_error"]=> int(1)
      ["error_message"]=> string(48) "Mandatory key(s) missing from params array: text"
    }
    ["message":protected]=>  string(48) "Mandatory key(s) missing from params array: text"
    ["string":"Exception":private]=>string(0) ""
    ["code":protected]=> int(0)
    ["file":protected]=> string(83) "sites/all/modules/contrib/civicrm/api/api.php"
    ["line":protected]=>  int(133)
    ["trace":"Exception":private]=> array(18) {
      [0]=> array(4) {
        ["file"]=> string(112) "[...]/vendor/civicrm/civicrm.sms.conversations/CRM/SmsConversation/Processor.php"
        ["line"]=> int(106)
        ["function"]=>string(12) "civicrm_api3"
        ["args"]=>
        array(3) {
          [0]=> string(7) "Contact"
          [1]=>  string(3) "sms"
```

Relevant bit of code:

```
  static function sendSMS($contactId, $text, $sourceContactId = NULL) {
    $result = civicrm_api3('Contact', 'sms', array(
      'contact_id' => $contactId,
      'source_contact_id' => $sourceContactId,
      'text' => $text, 
    ));

```

The extension was updated July 30, or at least, I logged it then. It's possible that someone else did the upgrade (but did not log the change in git). I don't remember but we would have a github issue if I did it.

**Comment by mlutfy** [comment]
Digging a bit more in the code, it might be from here:

```
    if (!$isValidAnswer) {
      // Send the invalid message
      CRM_SmsConversation_Processor::sendSMS($this->sourceContactId, $convQuestion['text_invalid'], $convContact['source_contact_id']);
```

I don't know enough about this extension, but it seems to me like if someone replies an invalid response, then the system crashes.

Maybe I'm just looking at a specific error report in the logs, and it's not representative.

but I don't think it's a simple bug. Either something broke upstream (in the "smsconversation" extension), or there is a configuration error (missing "text invalid message", missing valid options).

I am not very familiar with the extension.

Is there a way we can reproduce the error reliably? Such as resending the webhook?

The responses do seem to be logged in the system, but the conversation is not being processed (for further questions).

**Comment by turnerd** [comment]
Thanks Mathieu. I think the responses have been valid since this is an experienced user. They've reproduced the error 2 times; do you mean a way that we could reproduce it ourselves? I can investigate how to do that from their site. I got the Telerivet credentials as well and will examine the configuration there in case anything changed.
